version: '3'

services:

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  mysql8:
    container_name: mysql
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
#      设置初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
#      注意这里我映射为了 13306 端口
      - "13306:3306"